version: '3.7'
services:
  pgadmin:
    ports:
      - "5050:80"
    networks:
      - postgres-network
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ii@projeto.com
      PGADMIN_DEFAULT_PASSWORD: iiprojeto
    volumes:
       - pgadmin:/root/.pgadmin
    restart: unless-stopped

  postgres:
    ports:
      - "5432:5432"
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - postgres-network
    restart: unless-stopped
networks:
  postgres-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:

